name: Download and convert xml feed

on:
  schedule:
    - cron: '0 * * * *'  # Запускается каждый час
  push:
    paths:
      - '.github/workflows/download_cars.yml'

jobs:
  download_cars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install xml2json tool
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install xmltodict
        pip3 install requests

    - name: LS
      run: |
        ls -al
        ls -al public/

    - name: Convert XML to JSON
      run: |
        python3 -c "import xmltodict, json, sys, requests;
        url = 'https://export.maxposter.ru/autospot/6372.xml'
        response = requests.get(url)

        # Проверка успешности запроса
        response.raise_for_status()

        xml_data = response.text

        def transform_values(item):
            if isinstance(item, dict):
                for key in item:
                    item[key] = transform_values(item[key])
            elif isinstance(item, list):
                for idx, val in enumerate(item):
                    item[idx] = transform_values(val)
            elif item == '':
                return ""
            elif item.isdigit():
                return int(item)
            return item

        parsed_data = xmltodict.parse(xml_data, xml_attribs=False, force_list=False, force_cdata=False)
        transformed_data = transform_values(parsed_data)

        # Конвертация из XML в JSON
        print(json.dumps(transformed_data, ensure_ascii=False))" > public/cars.json

    - name: LS
      run: |
        ls -al
        ls -al public/

    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_ENV
      continue-on-error: true

    - name: Commit changes
      if: env.changes == 'true'
      run: |
        git config --local user.email "support+actions@github.com"
        git config --local user.name "github-actions-bot"
        git add public/cars.json
        git commit -m "Update cars.json due to detected changes"
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
